package net.minecraft.server;

public class CustomWorldSettingsFinal {

    public final float a;
    public final float b;
    public final float c;
    public final float d;
    public final float e;
    public final float f;
    public final float g;
    public final float h;
    public final float i;
    public final float j;
    public final float k;
    public final float l;
    public final float m;
    public final float n;
    public final float o;
    public final float p;
    public final int q;
    public final boolean r;
    public final boolean s;
    public final int t;
    public final boolean u;
    public final boolean v;
    public final boolean w;
    public final boolean x;
    public final boolean y;
    public final boolean z;
    public final boolean A;
    public final int B;
    public final boolean C;
    public final int D;
    public final boolean E;
    public final int F;
    public final int G;
    public final int H;
    public final int I;
    public final int J;
    public final int K;
    public final int L;
    public final int M;
    public final int N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final int T;
    public final int U;
    public final int V;
    public final int W;
    public final int X;
    public final int Y;
    public final int Z;
    public final int aa;
    public final int ab;
    public final int ac;
    public final int ad;
    public final int ae;
    public final int af;
    public final int ag;
    public final int ah;
    public final int ai;
    public final int aj;
    public final int ak;
    public final int al;
    public final int am;
    public final int an;
    public final int ao;
    public final int ap;
    public final int aq;
    public final int ar;
    public final int as;
    public final int at;
    public final int au;
    public final int av;
    public final int aw;
    public final int ax;
    public final int ay;
    public final int az;

    private CustomWorldSettingsFinal(CustomWorldSettings customworldsettings) {
        this.a = customworldsettings.b;
        this.b = customworldsettings.c;
        this.c = customworldsettings.d;
        this.d = customworldsettings.e;
        this.e = customworldsettings.f;
        this.f = customworldsettings.g;
        this.g = customworldsettings.h;
        this.h = customworldsettings.i;
        this.i = customworldsettings.j;
        this.j = customworldsettings.k;
        this.k = customworldsettings.l;
        this.l = customworldsettings.m;
        this.m = customworldsettings.n;
        this.n = customworldsettings.o;
        this.o = customworldsettings.p;
        this.p = customworldsettings.q;
        this.q = customworldsettings.r;
        this.r = customworldsettings.s;
        this.s = customworldsettings.t;
        this.t = customworldsettings.u;
        this.u = customworldsettings.v;
        this.v = customworldsettings.w;
        this.w = customworldsettings.x;
        this.x = customworldsettings.y;
        this.y = customworldsettings.z;
        this.z = customworldsettings.A;
        this.A = customworldsettings.B;
        this.B = customworldsettings.C;
        this.C = customworldsettings.D;
        this.D = customworldsettings.E;
        this.E = customworldsettings.F;
        this.F = customworldsettings.G;
        this.G = customworldsettings.H;
        this.H = customworldsettings.I;
        this.I = customworldsettings.J;
        this.J = customworldsettings.K;
        this.K = customworldsettings.L;
        this.L = customworldsettings.M;
        this.M = customworldsettings.N;
        this.N = customworldsettings.O;
        this.O = customworldsettings.P;
        this.P = customworldsettings.Q;
        this.Q = customworldsettings.R;
        this.R = customworldsettings.S;
        this.S = customworldsettings.T;
        this.T = customworldsettings.U;
        this.U = customworldsettings.V;
        this.V = customworldsettings.W;
        this.W = customworldsettings.X;
        this.X = customworldsettings.Y;
        this.Y = customworldsettings.Z;
        this.Z = customworldsettings.aa;
        this.aa = customworldsettings.ab;
        this.ab = customworldsettings.ac;
        this.ac = customworldsettings.ad;
        this.ad = customworldsettings.ae;
        this.ae = customworldsettings.af;
        this.af = customworldsettings.ag;
        this.ag = customworldsettings.ah;
        this.ah = customworldsettings.ai;
        this.ai = customworldsettings.aj;
        this.aj = customworldsettings.ak;
        this.ak = customworldsettings.al;
        this.al = customworldsettings.am;
        this.am = customworldsettings.an;
        this.an = customworldsettings.ao;
        this.ao = customworldsettings.ap;
        this.ap = customworldsettings.aq;
        this.aq = customworldsettings.ar;
        this.ar = customworldsettings.as;
        this.as = customworldsettings.at;
        this.at = customworldsettings.au;
        this.au = customworldsettings.av;
        this.av = customworldsettings.aw;
        this.aw = customworldsettings.ax;
        this.ax = customworldsettings.ay;
        this.ay = customworldsettings.az;
        this.az = customworldsettings.aA;
    }

    CustomWorldSettingsFinal(CustomWorldSettings customworldsettings, EmptyClass4 emptyclass4) {
        this(customworldsettings);
    }
}
